### ISSUE TITLE
Add makeRef and makeSTRef

### ISSUE THREAD

**Issue by texastoland** [zudov/purescript-var#4]
Seems possible. Would it be desirable?

**Comment by zudov** [comment]
I remember I wanted that and tried quite hard to make `get`, `set`, `update` work with `Ref` and other stuff out-of-box, but couldn't find a nice design that would allow it.

Row types are making it quite difficult, since they can't appear in the instance head. That's why we aren't able to say "when `get` is given `Ref a` it should result in `Eff (ref :: REF | r) s`". So what we do is we define `Var :: # ! -> * -> *` and then say that "when `get` is given `Var eff a` it should result in `Eff eff a`.

One thing which would make things nicer here is adding `fromRef :: forall eff. Ref a -> Var (ref :: REF | eff) a` which would allow using `Ref` fairly easily. There were some troubles with it before (see https://github.com/purescript/purescript/issues/1440), but they seem to be resolved now.

`get`, `set`, `update` are also restricted to `Eff`, which makes `ST` not possible. Perhaps that's not necessary and instead we can put `m` variable in the head, but IIRC it doesn't play well without functional dependency.

**Comment by texastoland** [comment]
> Row types are making it quite difficult…

This didn't make any sense to me when  but was tremendously helpful when I tried it myself!

> One thing which would make things nicer here is adding `fromRef`…

Ugh amazing. Perhaps you don't need to add anything except to your example?

``` hs
fromRef ref = makeVar (readRef ref) (writeRef ref)
fromSTRef ref = makeVar (readSTRef ref) (writeSTRef' ref)
-- fixed in purescript/purescript-st#5
writeSTRef' ref val = const unit <$> writeSTRef ref val

main = do
  counter <- fromSTRef <$> newSTRef 7
  counter $= 0            -- set counter to 0
  get counter >>= logShow -- => 0
  counter $= 2            -- set counter to 2
  get counter >>= logShow -- => 2
  counter $~ (_ * 5)      -- multiply counter by 5
  get counter >>= logShow -- => 10
```

**Comment by zudov** [comment]
We could add such conversion functions to the library, perhaps in a separate module.

**Comment by texastoland** [comment]
Both packages only depend on `Eff`. I'd be willing to PR here?

**Comment by zudov** [comment]
Yes, a PR would be great. Although, I think I'd like `from*` names more than `make*`, I would expect `makeRef` to return `Ref` rather than taking `Ref` and returning `Var`.

**Comment by zudov** [comment]
Hmm, now with functional dependencies there could be a better way here.
